Repository Boeing/config-file-validator, pull requests merged in 2023-10, with the labels that each got.

#48 feat: Auto release go binaries
  .github/workflows/release.yml
Labels: OSS Community Contribution

#50 Update Go version to 1.21 from 1.19
  .github/workflows/go.yml
  .github/workflows/release.yml
  Dockerfile
  go.mod
  go.sum
  pkg/finder/fsfinder.go
Labels: OSS Community Contribution, hacktoberfest-accepted, hacktoberfest

#52 feat(validation): Add support for properties files
  README.md
  go.mod
  go.sum
  pkg/filetype/file_type.go
  pkg/reporter/reporter_test.go
  pkg/reporter/stdout_reporter.go
  pkg/validator/properties.go
  pkg/validator/validator_test.go
  test/fixtures/good.properties
  test/fixtures/subdir2/bad.properties
Labels: OSS Community Contribution, hacktoberfest-accepted, hacktoberfest

#58 docs: add the install guide using aqua
  README.md
Labels: OSS Community Contribution, hacktoberfest-accepted, hacktoberfest

#55 Update readme to clarify current state of schema validation
  README.md
Labels: OSS Community Contribution, hacktoberfest-accepted, hacktoberfest

#56 feat(ci/cd): Add container image packages to release github action
  .github/workflows/release.yml
  Dockerfile
Labels: OSS Community Contribution, hacktoberfest-accepted, hacktoberfest

#59 #9 Add support for HCL files
  README.md
  cmd/validator/validator.go
  go.mod
  go.sum
  index.md
  pkg/filetype/file_type.go
  pkg/validator/hcl.go
  pkg/validator/validator_test.go
  test/fixtures/good.hcl
  test/fixtures/subdir2/bad.hcl
Labels: OSS Community Contribution, hacktoberfest-accepted, hacktoberfest

#65 chore: replace deprecated use of ioutil.ReadFile with os.ReadFile
  pkg/cli/cli.go
Labels: OSS Community Contribution, hacktoberfest-accepted, hacktoberfest

#62 Add --version to print the config-file-validator release tag
  .github/workflows/release.yml
  Dockerfile
  cmd/validator/validator.go
  cmd/validator/validator_test.go
  version.go
Labels: OSS Community Contribution, hacktoberfest-accepted, hacktoberfest

#54 Add option to turn off or limit the depth of recursive scanning
  cmd/validator/validator.go
  pkg/finder/finder_test.go
  pkg/finder/fsfinder.go
  test/fixtures/with-depth/additional-depth/sample.json
  test/fixtures/with-depth/sample.json
Labels: OSS Community Contribution, hacktoberfest-accepted, hacktoberfest

#53 feat(finder): Add support for multiple search paths
  cmd/validator/validator.go
  cmd/validator/validator_test.go
  index.md
  pkg/cli/cli_test.go
  pkg/finder/finder_test.go
  pkg/finder/fsfinder.go
Labels: OSS Community Contribution, hacktoberfest-accepted, hacktoberfest

#67 Add support for csv file type validation
  cmd/validator/validator.go
  index.md
  pkg/filetype/file_type.go
  pkg/validator/csv.go
  pkg/validator/validator_test.go
  test/fixtures/good.csv
  test/fixtures/subdir2/bad.csv
Labels: OSS Community Contribution, hacktoberfest-accepted, hacktoberfest

#68 Add support for Apple file list types for validation
  cmd/validator/validator.go
  go.mod
  go.sum
  index.md
  pkg/filetype/file_type.go
  pkg/validator/plist.go
  pkg/validator/validator_test.go
  test/fixtures/good.plist
  test/fixtures/subdir2/bad.plist
Labels: OSS Community Contribution, hacktoberfest-accepted, hacktoberfest

#72 Add Unit Test Coverage Threshold and Badge
  .github/workflows/go.yml
  README.md
  index.md
Labels: CI/CD

#81 add PKGBBUILD for Archlinux #63
  PKGBUILD
Labels: OSS Community Contribution, hacktoberfest-accepted, hacktoberfest
