Repository Boeing/config-file-validator, pull requests merged in 2024-10, with the labels that each got.

#180 Add PKGBUILD for Arch User Repository
  .github/workflows/release.yml
  PKGBUILD
Labels: hacktoberfest-accepted, hacktoberfest :jack_o_lantern:, waiting-on-maintainer-review

#177 Support env variables for config (#111)
  README.md
  cmd/validator/validator.go
Labels: hacktoberfest-accepted, hacktoberfest :jack_o_lantern:

#166 Add SARIF as a reporter option
  cmd/validator/validator.go
  cmd/validator/validator_test.go
  pkg/reporter/reporter_test.go
  pkg/reporter/sarif_reporter.go
  test/output/example/result.sarif
Labels: hacktoberfest-accepted, hacktoberfest :jack_o_lantern:

#191 [ISSUE-190] Update go version in `go.mod` to use 1.N.P format
  go.mod
  go.sum
Labels: hacktoberfest-accepted, hacktoberfest :jack_o_lantern:

#178 Display excludeable file types and validate
  cmd/validator/validator.go
Labels: hacktoberfest-accepted, hacktoberfest :jack_o_lantern:, pr-action-requested

#185 docs: replace example images with gif from terminalizer
  README.md
  img/custom_recursion.gif
  img/custom_recursion.png
  img/custom_reporter.gif
  img/custom_reporter.png
  img/exclude_dirs.gif
  img/exclude_dirs.png
  img/exclude_file_types.gif
  img/exclude_file_types.png
  img/gb-filetype-and-pass-fail.gif
  img/gb-filetype-and-pass-fail.png
  img/gb-filetype.gif
  img/gb-filetype.png
  img/multiple_paths.gif
  img/multiple_paths.png
  img/standard_run.gif
  img/standard_run.png
Labels: hacktoberfest-accepted, hacktoberfest :jack_o_lantern:, pr-action-requested
