Repository Boeing/config-file-validator, pull requests merged in 2024-08, with the labels that each got.

#157 EditorConfig file type #145
  go.mod
  go.sum
  pkg/filetype/file_type.go
  pkg/validator/editorconfig.go
  pkg/validator/validator_test.go
  test/fixtures/good.editorconfig
  test/fixtures/subdir2/bad.editorconfig
Labels: waiting-on-maintainer-review

#136 small optimization for fsfinder
  pkg/finder/finder_test.go
  pkg/finder/fsfinder.go
Labels: OSS Community Contribution

#162 fix(paths): trim leading and trailing whitespaces for file system paths
  pkg/finder/finder_test.go
  pkg/finder/fsfinder.go
Labels: waiting-on-maintainer-review

#168 Add Scoop installation reference in the readme
  README.md
  index.md
Labels: pr-action-requested
