Repository Boeing/config-file-validator, pull requests merged in 2024-03, with the labels that each got.

#115 Optimize element lookup in FileSystemFinder by switching from []string to map[string]struct{}
  pkg/filetype/file_type.go
  pkg/finder/finder_test.go
  pkg/finder/fsfinder.go
  pkg/misc/arrToMap.go
Labels: OSS Community Contribution, pr-action-requested

#122 Add: Contributors to website index.md
  README.md
  index.md
Labels: OSS Community Contribution

#121 Add support for .env config files #110
  go.mod
  go.sum
  pkg/filetype/file_type.go
  pkg/validator/env.go
  pkg/validator/validator_test.go
  test/fixtures/good.env
  test/fixtures/subdir2/bad.env
Labels: OSS Community Contribution, waiting-on-maintainer-review

#119 small refactoring of findOne func
  pkg/finder/fsfinder.go
Labels: OSS Community Contribution

#127 fix typos and brand names
  CONTRIBUTING.md
  README.md
  cmd/validator/validator.go
  index.md
  pkg/finder/finder_test.go
Labels: OSS Community Contribution
